train:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: -5.11
        std: 4.28
inference:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: -5.11
        std: 4.28
