defaults:
  - model: conformer
  - metrics: beam_search
  - datasets: custom # we do not want to run inference on training data
  - dataloader: custom
  - transforms: main
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 50
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_preds_path: "predictions" # path for saving predictions
  save_targets_path: null # None if dont want to save targets
  seed: 1
  from_pretrained: null # path to the pretrained model
datasets:
  custom:
    data_dir: test_data
