defaults:
  - model: conformer
  - metrics: beam_search
  - datasets: custom # we do not want to run inference on training data
  - dataloader: custom
  - transforms: main
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 50
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predictions" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "./saved/fm-SM-long/model_best.pth" # path to the pretrained model
datasets:
  custom:
    data_dir: test_data
