train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  wav_augs: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.PitchShift
        pitch_factor: [-3, 3]
        sample_rate: 16000
        p: 0
      - _target_: src.transforms.wav_augs.TimeStretch
        stretch_factor: [0.9, 1.1]
        p: 0
      - _target_: src.transforms.wav_augs.Noise
        std: 0.005
        p: 0
      - _target_: src.transforms.wav_augs.Gain
        min_gain_in_db: -15
        max_gain_in_db: 6
        p: 0
  spec_augs:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.TimeFreqMasking
        freq_size: 20
        time_size: 100

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
